### PR TITLE
Update gradle-wrapper.properties

### PR DESCRIPTION
**Pull request by JakobsCode**
Now working with newer version of Java8.

### CODE REVIEW

**Comment by henkelmax** [comment]
I generally don't update gradle to non-release versions. Is there a reason this is needed?

**Comment by JakobsCode** [comment]
If you install the latest version of Java.com (on windows 11):
CMD: Java --version ->
java 19.0.1 2022-10-18
Java(TM) SE Runtime Environment (build 19.0.1+10-21)
Java HotSpot(TM) 64-Bit Server VM (build 19.0.1+10-21, mixed mode, sharing)

then you get the following error message with Gradle:
BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 63

Only with this new version of Gradle the error message does not appear and you can use and develop the mod without any problems.

**Comment by JakobsCode** [comment]
Ich sehe gerade, du kommst auch aus Deutschland. Hätte mir das ganze übersetzten sparen können 😄

**Comment by henkelmax** [comment]
> If you install the latest version of Java.com (on windows 11):
> 
> CMD: Java --version ->
> 
> java 19.0.1 2022-10-18
> 
> Java(TM) SE Runtime Environment (build 19.0.1+10-21)
> 
> Java HotSpot(TM) 64-Bit Server VM (build 19.0.1+10-21, mixed mode, sharing)
> 
> 
> 
> then you get the following error message with Gradle:
> 
> BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 63
> 
> 
> 
> Only with this new version of Gradle the error message does not appear and you can use and develop the mod without any problems.

The latest Minecraft version uses Java 17. I generally avoid using different java versions than the version its compiled for in development.

**Pull request closed without merging**
