### PR TITLE
Vanilla-ish Tatar Translation!

### PR DESCRIPTION
**Pull request by Amirhan-Taipovjan-Greatest-I**
Vanilla-ish Tatar Translation almost done, but I still have some questions before merging PR:
- Verb "press" from "message.voicechat.mute.X"*, "message.voicechat.disable.X"*, "message.voicechat.hide_icons.X"* etc strings is in Imperative Mood... or it is Infinitive Form?

`*` — X means all translation keys under key group. For example "message.voicechat.hide_icons.X" means "message.voicechat.hide_icons.enabled" and "message.voicechat.hide_icons.disabled".

### CODE REVIEW

**Comment by henkelmax** [comment]
> Verb "press" from "message.voicechat.mute.X", "message.voicechat.disable.X", "message.voicechat.hide_icons.X"* etc strings is in Imperative Mood... or it is Infinitive Form?

This is shown when hovering over the button, telling the user what pressing the button does.

**Comment by Amirhan-Taipovjan-Greatest-I** [comment]
> > Verb "press" from "message.voicechat.mute.X", "message.voicechat.disable.X", "message.voicechat.hide_icons.X"* etc strings is in Imperative Mood... or it is Infinitive Form?
> 
> This is shown when hovering over the button, telling the user what pressing the button does.
> 
> 

Is it mean that "press" is in Imperative Mood?

**Comment by henkelmax** [comment]
> > > Verb "press" from "message.voicechat.mute.X", "message.voicechat.disable.X", "message.voicechat.hide_icons.X"* etc strings is in Imperative Mood... or it is Infinitive Form?
> > 
> > 
> > This is shown when hovering over the button, telling the user what pressing the button does.
> 
> Is it mean that "press" is in Imperative Mood?

I guess so

**Comment by Amirhan-Taipovjan-Greatest-I** [comment]
> > > > Verb "press" from "message.voicechat.mute.X", "message.voicechat.disable.X", "message.voicechat.hide_icons.X"* etc strings is in Imperative Mood... or it is Infinitive Form?
> > > 
> > > 
> > > This is shown when hovering over the button, telling the user what pressing the button does.
> > 
> > 
> > Is it mean that "press" is in Imperative Mood?
> 
> I guess so

Thank You for the info! Now... translation is ready to be merged!

**Comment by henkelmax** [comment]
Thank you!

**Pull request merged**
