### PR TITLE
Update ja_jp.json

### PR DESCRIPTION
**Pull request by ookkoouu**
- Add untranslated content
- Revamp translation

This PR includes the changes made in #736.

### CODE REVIEW

**Comment by ookkoouu** [comment]
By adding keys `"modmenu.summaryTranslation.voicechat"` and `"modmenu.descriptionTranslation.voicechat"`, we translated the summary of ModMenu.

svc

**Comment by Greg-21** [comment]
Shouldn't these types of translation keys that are only applicable to specific platforms be placed in their designated directories (in this case, Fabric and Quilt with the Fabric compatibility layer, since Prospector's Mod Menu has always been a Fabric-exclusive mod) rather than in the shared "common" directory to avoid unnecessary clutter?

This question is primarily directed to @henkelmax rather than you.

**Comment by henkelmax** [comment]
Thats alright. If the translations don't exist, they just get ignored.

**Comment by henkelmax** [comment]
Thank you!

**Pull request merged**
