### PR TITLE
Add support for Bukkit-based 1.8.8 servers

### PR DESCRIPTION
**Pull request by hpfxd**
This patch does not modify any other platform implementations such as Fabric or Forge, this is purely for servers running 1.8.8 which wish to support clients using the mod on newer clients connecting with ViaVersion.

Usages of Bukkit's `NamespacedKey` class were changed to Adventure's `Key`, as this class was not present in 1.8.8. The former actually implements the latter in modern versions of Paper.

I am not sure if this patch is something that would be accepted into the project, but I made it mostly for personal use and figured some other people may benefit from it :)

### CODE REVIEW

**Comment by henkelmax** [comment]
Hey, thank you for your contribution!
Could you add support for all 1.8 versions? Sites like spigot only let you specify the major Minecraft version, so this would lead to confusion for people trying to install it on any other 1.8 version.

**Comment by hpfxd** [comment]
The only other versions of 1.8.x that Spigot has released builds for were 1.8 and 1.8.3. I've added support in the compatibility system and attempted to test, but it seems like it doesn't work due to some log4j methods missing on these versions, which would require some much bigger changes to get working. ViaVersion (as well as pretty much any other reasonably popular plugin) seems to not support either of these versions anyway, so there wouldn't be much point in using them.

**Comment by henkelmax** [comment]
Good point, but it seems bukkit supports some more 1.8 versions.
image

But you are right, nobody is gonna use that anyways. I'm looking into your code once I have some time and merge it.

**Comment by henkelmax** [comment]
Works perfectly fine, thanks!

**Pull request merged**
