### PR TITLE
Update zh_cn.json

### PR DESCRIPTION
**Pull request by karllee830**
Translate more configurations

### CODE REVIEW

**Comment by henkelmax** [comment]
Thank you!

**Comment by karllee830** [comment]
Can you add my name to credits list?
thank you!
https://modrepo.de/minecraft/voicechat/credits

**Comment by henkelmax** [comment]
Already did. It just takes a while until I merge it into the production version.
https://dev.modrepo.de/minecraft/voicechat/credits

**Comment by karllee830** [comment]
thank you very much!

**Pull request merged**
